from __future__ import annotations

from pathlib import Path

from universal_ai_foundry.blueprints import get_blueprint
from universal_ai_foundry.io import write_manifest


PLACEHOLDER_FILES = {
    "README.md": "# AI Capsule\n\nThis capsule was generated by Universal AI Foundry.\n",
    "datasets/.gitkeep": "",
    "models/.gitkeep": "",
    "outputs/.gitkeep": "",
    "recipes/README.md": "# Recipes\n\nPlace training recipe scripts here.\n",
}


def scaffold_capsule(target_dir: Path, blueprint_name: str) -> Path:
    manifest = get_blueprint(blueprint_name)
    manifest.name = target_dir.name
    target_dir.mkdir(parents=True, exist_ok=True)
    for relative_path, content in PLACEHOLDER_FILES.items():
        file_path = target_dir / relative_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content, encoding="utf-8")
    write_manifest(target_dir / "capsule.json", manifest)
    return target_dir / "capsule.json"

